model:
  in_channels: 3
  latent_dim: 128
  hidden_dims:
  - 32
  - 64
  - 128
  - 256
  - 512
  mid_inflate: 2
  mid_dim: 2048
  lr: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
