name: Lint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - uses: eifinger/setup-rye@v2
        id: setup-rye
      - name: Use UV instead of pip
        run: rye config --set-bool behavior.use-uv=true
      - name: Install dependencies
        run: |
          rye sync
      - name: Lint and Format
        run: |
          rye fmt
          rye lint
