name: Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
      - uses: eifinger/setup-rye@v2
        id: setup-rye
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          rye sync
      - name: Run pytest
        run: |
          rye run pytest --cov=encyclopedia_vae tests -v
